import type { Metadata } from "next";

import "./globals.css";
import { LoginDialog } from "@/components/LoginForm";


export const metadata: Metadata = {
  title: "notebook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <div id="root" className="bg-slate-100">
          <div className="content w-screen h-screen overflow-y-auto" >
            {children}
            <LoginDialog />
          </div>
        </div>
      </body>
    </html>
  );
}
