import type { Metadata } from "next";

import "./globals.css";
import { LoginDialog } from "@/components/LoginForm";
import type { Viewport } from 'next'
import Script from "next/script";


export const viewport: Viewport = {
  initialScale: 1,
  minimumScale: 1,
  maximumScale: 1,
  userScalable: false,
  width: 'device-width',
}

export const metadata: Metadata = {
  title: "notebook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" style={{fontSize: 14 }}>
      <body>
        <div id="root" className="bg-slate-50">
          <div className="content w-screen h-dvh overflow-y-auto" >
            {children}
            <LoginDialog />
          </div>
        </div>
      </body>
    </html>
  );
}
